#### general settings
name: entropy-refusion
use_tb_logger: true
model: denoising
distortion: low-light
gpu_ids: [0]

sde:
  max_sigma: 50
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /datasets/low-light/LOLv1/Train/target
    dataroot_LQ: /datasets/low-light/LOLv1/Train/input

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 8
    GT_size: 128
    LR_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /datasets/low-light/LOLv1/Test/target
    dataroot_LQ: /datasets/low-light/LOLv1/Test/input


#### network structures
network_G:
  which_model_G: ConditionalNAFNet
  setting:
    width: 64
    enc_blk_nums: [1, 1, 1, 1, 28]
    middle_blk_num: 1
    dec_blk_nums: [1, 1, 1, 1, 1]

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~ 

#### training settings: learning rate scheme, loss
train:
  optimizer: AdamW # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 500000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-6

  # criterion
  is_weighted: False
  loss_type: en
  weight: 1.0
  pixel_level: 32

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 1e4
